/**
 * Stable, machine-readable error codes.
 *
 * These are part of the public API contract: clients branch on `error.code`,
 * never on the human-readable `message`. Codes may be added freely, but an
 * existing code must not change meaning once a client has shipped against it.
 *
 * Domain-specific codes (INSUFFICIENT_CREDIT, ORDER_NOT_CANCELLABLE, ...) are
 * added by their owning module as those modules are built.
 */
export const ERROR_CODES = Object.freeze({
  // Client errors
  BAD_REQUEST: 'BAD_REQUEST',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  MALFORMED_JSON: 'MALFORMED_JSON',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
  METHOD_NOT_ALLOWED: 'METHOD_NOT_ALLOWED',
  CONFLICT: 'CONFLICT',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // --- Identity & access ---------------------------------------------------
  // Login always answers INVALID_CREDENTIALS, whether the account is unknown or
  // the password is wrong. A distinct "no such user" reply would let an
  // attacker enumerate registered phone numbers.
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_ALREADY_EXISTS: 'ACCOUNT_ALREADY_EXISTS',
  ACCOUNT_BLOCKED: 'ACCOUNT_BLOCKED',
  ACCOUNT_DELETED: 'ACCOUNT_DELETED',
  PASSWORD_NOT_SET: 'PASSWORD_NOT_SET',

  TOKEN_MISSING: 'TOKEN_MISSING',
  TOKEN_INVALID: 'TOKEN_INVALID',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_WRONG_TYPE: 'TOKEN_WRONG_TYPE',
  /// Security event: a rotated refresh token was replayed. Revokes the session.
  TOKEN_REUSE_DETECTED: 'TOKEN_REUSE_DETECTED',

  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_REVOKED: 'SESSION_REVOKED',
  SESSION_EXPIRED: 'SESSION_EXPIRED',

  // OTP. Verification failures all collapse to OTP_INVALID so a caller cannot
  // distinguish "no such challenge" from "wrong code" - either answer would
  // confirm whether the identifier is registered.
  OTP_INVALID: 'OTP_INVALID',
  OTP_ATTEMPTS_EXCEEDED: 'OTP_ATTEMPTS_EXCEEDED',
  OTP_RATE_LIMITED: 'OTP_RATE_LIMITED',
  OTP_RESEND_TOO_SOON: 'OTP_RESEND_TOO_SOON',

  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  WRONG_PRINCIPAL: 'WRONG_PRINCIPAL',
  NOT_RESOURCE_OWNER: 'NOT_RESOURCE_OWNER',
  USER_NOT_FOUND: 'USER_NOT_FOUND',

  // --- Customer ------------------------------------------------------------
  PROFILE_ALREADY_EXISTS: 'PROFILE_ALREADY_EXISTS',
  PROFILE_NOT_FOUND: 'PROFILE_NOT_FOUND',
  ADDRESS_LIMIT_REACHED: 'ADDRESS_LIMIT_REACHED',

  // --- Corporate -----------------------------------------------------------
  // Login-gate reasons are distinct on purpose: each needs a different screen
  // and a different support answer (docs/10 §4.4).
  CORPORATE_VERIFICATION_PENDING: 'CORPORATE_VERIFICATION_PENDING',
  CORPORATE_VERIFICATION_REJECTED: 'CORPORATE_VERIFICATION_REJECTED',
  CORPORATE_ACCOUNT_SUSPENDED: 'CORPORATE_ACCOUNT_SUSPENDED',
  CORPORATE_ACCOUNT_INACTIVE: 'CORPORATE_ACCOUNT_INACTIVE',

  CORPORATE_ALREADY_REGISTERED: 'CORPORATE_ALREADY_REGISTERED',
  CORPORATE_ALREADY_DECIDED: 'CORPORATE_ALREADY_DECIDED',
  NOT_CORPORATE_MEMBER: 'NOT_CORPORATE_MEMBER',
  ALREADY_CORPORATE_MEMBER: 'ALREADY_CORPORATE_MEMBER',
  INSUFFICIENT_CORPORATE_ROLE: 'INSUFFICIENT_CORPORATE_ROLE',
  ROLE_NOT_ASSIGNABLE: 'ROLE_NOT_ASSIGNABLE',
  CANNOT_MODIFY_OWNER: 'CANNOT_MODIFY_OWNER',
  LAST_OWNER_CANNOT_BE_REMOVED: 'LAST_OWNER_CANNOT_BE_REMOVED',
  CANNOT_REMOVE_SELF: 'CANNOT_REMOVE_SELF',

  // --- Fleet ---------------------------------------------------------------
  VEHICLE_RETIRED: 'VEHICLE_RETIRED',
  VEHICLE_NOT_DISPATCHABLE: 'VEHICLE_NOT_DISPATCHABLE',
  VEHICLE_ALREADY_ASSIGNED: 'VEHICLE_ALREADY_ASSIGNED',
  VEHICLE_NOT_ASSIGNED: 'VEHICLE_NOT_ASSIGNED',
  VEHICLE_HAS_OPEN_SHIFT: 'VEHICLE_HAS_OPEN_SHIFT',
  ASSIGNMENT_UNCHANGED: 'ASSIGNMENT_UNCHANGED',

  DRIVER_NOT_ACTIVE: 'DRIVER_NOT_ACTIVE',
  DRIVER_LICENCE_EXPIRED: 'DRIVER_LICENCE_EXPIRED',
  DRIVER_ALREADY_ASSIGNED: 'DRIVER_ALREADY_ASSIGNED',
  DRIVER_NOT_ASSIGNED_TO_VEHICLE: 'DRIVER_NOT_ASSIGNED_TO_VEHICLE',
  DRIVER_HAS_OPEN_SHIFT: 'DRIVER_HAS_OPEN_SHIFT',

  SHIFT_ALREADY_OPEN: 'SHIFT_ALREADY_OPEN',
  SHIFT_NOT_OPEN: 'SHIFT_NOT_OPEN',
  /// BR-307: a shift cannot close while the driver still holds an order.
  /// Distinct from SHIFT_NOT_OPEN so the app can say what to do about it.
  SHIFT_HAS_ACTIVE_ORDER: 'SHIFT_HAS_ACTIVE_ORDER',
  /// The driver app's own OTP path for verifying the receiver on site.
  DELIVERY_OTP_INVALID: 'DELIVERY_OTP_INVALID',
  DELIVERY_ALREADY_SUBMITTED: 'DELIVERY_ALREADY_SUBMITTED',

  INSUFFICIENT_FUEL: 'INSUFFICIENT_FUEL',
  EXCEEDS_CAPACITY: 'EXCEEDS_CAPACITY',
  METER_READING_REGRESSION: 'METER_READING_REGRESSION',
  METER_PHOTO_REQUIRED: 'METER_PHOTO_REQUIRED',

  // --- Pricing & catalog ---------------------------------------------------
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_INACTIVE: 'PRODUCT_INACTIVE',
  PRODUCT_CODE_TAKEN: 'PRODUCT_CODE_TAKEN',

  NO_ACTIVE_PRICE: 'NO_ACTIVE_PRICE',
  PRICE_OVERLAP: 'PRICE_OVERLAP',
  PRICE_OUT_OF_SANITY_BAND: 'PRICE_OUT_OF_SANITY_BAND',
  PRICE_NOT_PENDING_APPROVAL: 'PRICE_NOT_PENDING_APPROVAL',
  PRICE_ALREADY_SUPERSEDED: 'PRICE_ALREADY_SUPERSEDED',
  PRICE_EFFECTIVE_IN_PAST: 'PRICE_EFFECTIVE_IN_PAST',
  SELF_APPROVAL_FORBIDDEN: 'SELF_APPROVAL_FORBIDDEN',

  NO_DELIVERY_CHARGE_RULE: 'NO_DELIVERY_CHARGE_RULE',
  DELIVERY_CHARGE_TYPE_UNSUPPORTED: 'DELIVERY_CHARGE_TYPE_UNSUPPORTED',
  BELOW_MINIMUM_ORDER_QUANTITY: 'BELOW_MINIMUM_ORDER_QUANTITY',

  QUOTE_NOT_FOUND: 'QUOTE_NOT_FOUND',
  /// 410 Gone, not 409 - the quote is not in conflict with anything, it has
  /// ceased to exist as a usable thing (docs/10 §6).
  QUOTE_EXPIRED: 'QUOTE_EXPIRED',
  /// 409 - a state conflict, unlike the above. Easy pair to get wrong.
  QUOTE_ALREADY_USED: 'QUOTE_ALREADY_USED',
  PRICE_CHANGED: 'PRICE_CHANGED',
  BREAKDOWN_DOES_NOT_BALANCE: 'BREAKDOWN_DOES_NOT_BALANCE',

  // --- Ordering ------------------------------------------------------------
  // The first three are reserved by docs/10 §7.2 with these exact spellings.
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_NOT_CANCELLABLE: 'ORDER_NOT_CANCELLABLE',
  DUPLICATE_ORDER: 'DUPLICATE_ORDER',
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
  /// The transition exists but this actor may not drive it. Distinct from
  /// INVALID_STATE_TRANSITION so a client can tell "impossible" from "not
  /// yours to do".
  TRANSITION_NOT_PERMITTED: 'TRANSITION_NOT_PERMITTED',
  ORDER_ALREADY_TERMINAL: 'ORDER_ALREADY_TERMINAL',
  /// Cancellation is blocked in-app once a tanker is moving (BR-1202). The
  /// customer may request one; operations decides.
  CANCELLATION_REQUIRES_OPERATOR: 'CANCELLATION_REQUIRES_OPERATOR',
  PAYMENT_MODE_UNSUPPORTED: 'PAYMENT_MODE_UNSUPPORTED',

  // Reservations
  RESERVATION_NOT_FOUND: 'RESERVATION_NOT_FOUND',
  RESERVATION_ALREADY_HELD: 'RESERVATION_ALREADY_HELD',
  RESERVATION_NOT_HELD: 'RESERVATION_NOT_HELD',
  NO_VEHICLE_AVAILABLE: 'NO_VEHICLE_AVAILABLE',

  // --- Platform ------------------------------------------------------------
  IDEMPOTENCY_KEY_REQUIRED: 'IDEMPOTENCY_KEY_REQUIRED',
  /// The same key replayed with a DIFFERENT body. Returning the first response
  /// would silently discard this request (docs/10 §8.2).
  IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',
  /// The first attempt is still running. The client should retry shortly with
  /// the SAME key.
  IDEMPOTENCY_REQUEST_IN_PROGRESS: 'IDEMPOTENCY_REQUEST_IN_PROGRESS',

  // Server errors
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  DATABASE_ERROR: 'DATABASE_ERROR',
  DEPENDENCY_FAILURE: 'DEPENDENCY_FAILURE',
});
